export const TABLES = {
  MAIN_CATEGORIES: process.env.EXPO_PUBLIC_AWS_DYNAMODB_TABLE_MAIN_CATEGORIES,
  CATEGORIES: process.env.EXPO_PUBLIC_AWS_DYNAMODB_TABLE_CATEGORIES,
  MAIN_CATEGORY_SCHEDULES:
    process.env.EXPO_PUBLIC_AWS_DYNAMODB_TABLE_MAIN_CATEGORY_SCHEDULES,
  CATEGORY_SCHEDULES: process.env.EXPO_PUBLIC_AWS_DYNAMODB_TABLE_C_SCHEDULES,
} as const;
