export const TABLES = {
  ITEMS: process.env.EXPO_PUBLIC_AWS_DYNAMODB_TABLE_ITEMS,
  MAIN_CATEGORIES: process.env.EXPO_PUBLIC_AWS_DYNAMODB_TABLE_MAIN_CATEGORIES,
  CATEGORIES: process.env.EXPO_PUBLIC_AWS_DYNAMODB_TABLE_CATEGORIES,
  SUBCATEGORIES: process.env.EXPO_PUBLIC_AWS_DYNAMODB_TABLE_SUBCATEGORIES,
  MAIN_CATEGORY_SCHEDULES:
    process.env.EXPO_PUBLIC_AWS_DYNAMODB_TABLE_MAIN_CATEGORY_SCHEDULES,
  CATEGORY_SCHEDULES: process.env.EXPO_PUBLIC_AWS_DYNAMODB_TABLE_C_SCHEDULES,
  SUBCATEGORY_SCHEDULES:
    process.env.EXPO_PUBLIC_AWS_DYNAMODB_TABLE_SUBCATEGORY_SCHEDULES,
  ITEM_SCHEDULES: process.env.EXPO_PUBLIC_AWS_DYNAMODB_TABLE_ITEM_SCHEDULES,
} as const;
